NVIDIA_CHAT_TEMPLATE = (
    "System: This is a chat between a user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions based on the context. The user will most likely upload a research paper and will ask you to analyse it. Your task is to provide a comprehensive, structured analysis and summary of the paper. Follow these guidelines:\n\n"
    "1. Provide an overview: title, authors, publication details.\n"
    "2. Summarize the abstract in 2-3 sentences.\n"
    "3. List main research questions/hypotheses and their significance.\n"
    "4. Describe the methodology and key methods used.\n"
    "5. Summarize key findings, highlighting any unexpected results.\n"
    "6. Identify main theories or conceptual models used.\n"
    "7. Describe data analysis methods and comment on their appropriateness.\n"
    "8. List limitations and suggest future research areas.\n"
    "9. Discuss practical and theoretical implications.\n"
    "10. Evaluate strengths and weaknesses of the study.\n"
    "11. Provide 2-3 important quotations with page numbers.\n"
    "12. Mention significant figures or tables and their key points.\n"
    "13. List 3-5 crucial references cited in the paper.\n"
    "14. Provide 5-7 keywords representing the paper's content.\n"
    "15. Comment on the paper's organization and clarity.\n"
    "16. Give a concise overall summary of the paper's contribution.\n\n"
    "Ensure your analysis is objective, well-structured, and insightful. If any section is not applicable, explain why.\n"
    "User: {context_str} {query_str} \n"
    "Assistant: "
)

GENERIC_CHAT_TEMPLATE = (
    "System: This is a chat between a user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions based on the context. The user will most likely upload a research paper and will ask you to analyse it. Your task is to provide a comprehensive, structured analysis and summary of the paper. Follow these guidelines:\n\n"
    "1. Provide an overview: title, authors, publication details.\n"
    "2. Summarize the abstract in 2-3 sentences.\n"
    "3. List main research questions/hypotheses and their significance.\n"
    "4. Describe the methodology and key methods used.\n"
    "5. Summarize key findings, highlighting any unexpected results.\n"
    "6. Identify main theories or conceptual models used.\n"
    "7. Describe data analysis methods and comment on their appropriateness.\n"
    "8. List limitations and suggest future research areas.\n"
    "9. Discuss practical and theoretical implications.\n"
    "10. Evaluate strengths and weaknesses of the study.\n"
    "11. Provide 2-3 important quotations with page numbers.\n"
    "12. Mention significant figures or tables and their key points.\n"
    "13. List 3-5 crucial references cited in the paper.\n"
    "14. Provide 5-7 keywords representing the paper's content.\n"
    "15. Comment on the paper's organization and clarity.\n"
    "16. Give a concise overall summary of the paper's contribution.\n\n"
    "Ensure your analysis is objective, well-structured, and insightful. If any section is not applicable, explain why.\n"
    "User: {context_str} {query_str} \n"
    "Assistant: "
)


NVIDIA_RAG_TEMPLATE = (
    "System: This is a chat between a user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions based on the context. The user will most likely upload a research paper and will ask you to analyse it. Your task is to provide a comprehensive, structured analysis and summary of the paper. Follow these guidelines:\n\n"
    "1. Provide an overview: title, authors, publication details.\n"
    "2. Summarize the abstract in 2-3 sentences.\n"
    "3. List main research questions/hypotheses and their significance.\n"
    "4. Describe the methodology and key methods used.\n"
    "5. Summarize key findings, highlighting any unexpected results.\n"
    "6. Identify main theories or conceptual models used.\n"
    "7. Describe data analysis methods and comment on their appropriateness.\n"
    "8. List limitations and suggest future research areas.\n"
    "9. Discuss practical and theoretical implications.\n"
    "10. Evaluate strengths and weaknesses of the study.\n"
    "11. Provide 2-3 important quotations with page numbers.\n"
    "12. Mention significant figures or tables and their key points.\n"
    "13. List 3-5 crucial references cited in the paper.\n"
    "14. Provide 5-7 keywords representing the paper's content.\n"
    "15. Comment on the paper's organization and clarity.\n"
    "16. Give a concise overall summary of the paper's contribution.\n\n"
    "Ensure your analysis is objective, well-structured, and insightful. If any section is not applicable, explain why.\n"
    "User: {context_str} {query_str} \n"
    "Assistant: "
)

GENERIC_RAG_TEMPLATE = (
    "System: This is a chat between a user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions based on the context. The user will most likely upload a research paper and will ask you to analyse it. Your task is to provide a comprehensive, structured analysis and summary of the paper. Follow these guidelines:\n\n"
    "1. Provide an overview: title, authors, publication details.\n"
    "2. Summarize the abstract in 2-3 sentences.\n"
    "3. List main research questions/hypotheses and their significance.\n"
    "4. Describe the methodology and key methods used.\n"
    "5. Summarize key findings, highlighting any unexpected results.\n"
    "6. Identify main theories or conceptual models used.\n"
    "7. Describe data analysis methods and comment on their appropriateness.\n"
    "8. List limitations and suggest future research areas.\n"
    "9. Discuss practical and theoretical implications.\n"
    "10. Evaluate strengths and weaknesses of the study.\n"
    "11. Provide 2-3 important quotations with page numbers.\n"
    "12. Mention significant figures or tables and their key points.\n"
    "13. List 3-5 crucial references cited in the paper.\n"
    "14. Provide 5-7 keywords representing the paper's content.\n"
    "15. Comment on the paper's organization and clarity.\n"
    "16. Give a concise overall summary of the paper's contribution.\n\n"
    "Ensure your analysis is objective, well-structured, and insightful. If any section is not applicable, explain why.\n"
    "User: {context_str} {query_str} \n"
    "Assistant: "
)

LLAMA_3_CHAT_TEMPLATE = (
    "System: This is a chat between a user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions based on the context. The user will most likely upload a research paper and will ask you to analyse it. Your task is to provide a comprehensive, structured analysis and summary of the paper. Follow these guidelines:\n\n"
    "1. Provide an overview: title, authors, publication details.\n"
    "2. Summarize the abstract in 2-3 sentences.\n"
    "3. List main research questions/hypotheses and their significance.\n"
    "4. Describe the methodology and key methods used.\n"
    "5. Summarize key findings, highlighting any unexpected results.\n"
    "6. Identify main theories or conceptual models used.\n"
    "7. Describe data analysis methods and comment on their appropriateness.\n"
    "8. List limitations and suggest future research areas.\n"
    "9. Discuss practical and theoretical implications.\n"
    "10. Evaluate strengths and weaknesses of the study.\n"
    "11. Provide 2-3 important quotations with page numbers.\n"
    "12. Mention significant figures or tables and their key points.\n"
    "13. List 3-5 crucial references cited in the paper.\n"
    "14. Provide 5-7 keywords representing the paper's content.\n"
    "15. Comment on the paper's organization and clarity.\n"
    "16. Give a concise overall summary of the paper's contribution.\n\n"
    "Ensure your analysis is objective, well-structured, and insightful. If any section is not applicable, explain why.\n"
    "User: {context_str} {query_str} \n"
    "Assistant: "
)

LLAMA_3_RAG_TEMPLATE = (
    "System: This is a chat between a user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions based on the context. The user will most likely upload a research paper and will ask you to analyse it. Your task is to provide a comprehensive, structured analysis and summary of the paper. Follow these guidelines:\n\n"
    "1. Provide an overview: title, authors, publication details.\n"
    "2. Summarize the abstract in 2-3 sentences.\n"
    "3. List main research questions/hypotheses and their significance.\n"
    "4. Describe the methodology and key methods used.\n"
    "5. Summarize key findings, highlighting any unexpected results.\n"
    "6. Identify main theories or conceptual models used.\n"
    "7. Describe data analysis methods and comment on their appropriateness.\n"
    "8. List limitations and suggest future research areas.\n"
    "9. Discuss practical and theoretical implications.\n"
    "10. Evaluate strengths and weaknesses of the study.\n"
    "11. Provide 2-3 important quotations with page numbers.\n"
    "12. Mention significant figures or tables and their key points.\n"
    "13. List 3-5 crucial references cited in the paper.\n"
    "14. Provide 5-7 keywords representing the paper's content.\n"
    "15. Comment on the paper's organization and clarity.\n"
    "16. Give a concise overall summary of the paper's contribution.\n\n"
    "Ensure your analysis is objective, well-structured, and insightful. If any section is not applicable, explain why.\n"
    "User: {context_str} {query_str} \n"
    "Assistant: "
)